### ISSUE TITLE
Typo on set name for Astral Radiance on wiki page

### ISSUE THREAD

**Issue by Grimmys** [Pepper0ni/TTS-PTCG-Pack-Simulator#10]
On this page: https://github.com/Pepper0ni/TTS-PTCG-Pack-Simulator/wiki/Pull-rate-and-card-order-Information

Astral Radiance set is mistyped as "Astral Brilliance".

I can try to open a PR to fix it if you want.

**Comment by Pepper0ni** [comment]
fixed, Thanks
