### ISSUE TITLE
Missing pull rate data for Twilight Masquerade and Shrouded Fable?

### ISSUE THREAD

**Issue by aprct** [Pepper0ni/TTS-PTCG-Pack-Simulator#11]
Huge fan of your work Pepper0ni! 

It looks like the Steam Workshop item is up to date with Shrouded Fable, but the Wiki entry for this project doesn't have the pull rates for the last 2 sets up yet: https://github.com/Pepper0ni/TTS-PTCG-Pack-Simulator/wiki/Pull-rate-and-card-order-Information

Looking forward to the update!

**Comment by Pepper0ni** [comment]
Sorry I've been forgetting to do this part lately, just did it now, thanks for the bump
