### ISSUE TITLE
Sun and Moon - Unified Minds (SM11) dropSlots are not correct

### ISSUE THREAD

**Issue by MythicWebsite** [Pepper0ni/TTS-PTCG-Pack-Simulator#9]
This probably happens on more than just this set, but with how the names for the cards are generated, the slots become messed up because of the cards 79a, 191a, and 206a. Normally cards like these are generated to have a large number to be skipped over, but the drop slots for this set account for them to be named in order. This results in the slots being incorrect after those slots by 1,2 or 3 cards.

If you open them in-game you'll see that there's random uncommons and rares in the commons slots along with other slots being messed up.

**Comment by MythicWebsite** [comment]
Ran through every set and the only other set that was broken in this way was Sun and Moon - Unbroken Bonds (SM10).
Was broken due to the cards 182a, 182b, 189a, and 195a, resulting in the slots being incorrect by 2, 3 or 4 cards from those points.

**Comment by Pepper0ni** [comment]
Finally got to the bottom of this, the issue was a malformed data entry causing reverses to get mixed up with commons, not yellow A's. am going to go over the rest and fix them now
